package com.ezreal.demo.entity;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_id
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_name
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.owner_id
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.address
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.tel
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_id
     *
     * @return the value of tb_shop.shop_id
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_id
     *
     * @param shopId the value for tb_shop.shop_id
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_name
     *
     * @return the value of tb_shop.shop_name
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_name
     *
     * @param shopName the value for tb_shop.shop_name
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.owner_id
     *
     * @return the value of tb_shop.owner_id
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.owner_id
     *
     * @param ownerId the value for tb_shop.owner_id
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.address
     *
     * @return the value of tb_shop.address
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.address
     *
     * @param address the value for tb_shop.address
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.tel
     *
     * @return the value of tb_shop.tel
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.tel
     *
     * @param tel the value for tb_shop.tel
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }
}