package com.ezreal.demo.dao;

import com.ezreal.demo.entity.Shop;

import java.util.List;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    int deleteByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    Shop selectByPrimaryKey(Integer shopId);


    List<Shop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Mar 15 15:49:49 CST 2018
     */
    int updateByPrimaryKey(Shop record);
}